function(suppress_compiler_warnings target)
  get_target_property(target_type ${target} TYPE)

  if(${target_type} STREQUAL "INTERFACE_LIBRARY")
    get_target_property(target_include_dir ${target} INTERFACE_INCLUDE_DIRECTORIES)
    target_include_directories(${target} SYSTEM INTERFACE ${target_include_dir})
  else()
    if(MSVC)
      target_compile_options(${target} PRIVATE "/w")
    else()
      target_compile_options(${target} PRIVATE "-w")
    endif()
  endif()
endfunction()
