name: style

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release

jobs:
  check-style:
    name: Check Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install GMP and MPFR
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install libgmp-dev libmpfr-dev

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dfintamath_enable_clangformat=ON
        env:
          CC: gcc
          CXX: g++

      - name: Run clang-format
        working-directory: ${{github.workspace}}
        run: cmake --build build --target clangformat_check
